version: 2.1

jobs:
  build-ui:
    docker:
      - image: node:8.15.1
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: build ui
          command: |
            npm install
            npm run lint
            npm run build
  build-server:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: build server
          command: |
            dotnet restore
            dotnet publish -c release -o out -r linux-arm
  publish-image:
    docker:
      - image: docker:18.09.4
    working_directory: ~/client
    steps:
      - checkout
      - run: 
          name: publish image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t marcussmallman/ideas-client:latest -t marcussmallman/ideas-client:$CIRCLE_BRANCH .
            docker push marcussmallman/ideas-client:$CIRCLE_BRANCH

workflows:
  version: 2.1
  ideas:
    jobs:
      - build-ui
      - build-server
      - publish-image:
          requires:
            - build-ui
            - build-server