version: 2.1

jobs:
  build-ui:
    working_directory: /client
    docker:
      - image: node:8.15.1
    steps:
      - checkout
      - run:
          name: Build UI
          command: |
            npm install
            npm run lint
            npm run build
  build-server:
    working_directory: /client
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Build Server
          command: |
            dotnet restore
            dotnet publish -c release -o out -r linux-arm
  publish-image:
    working_directory: /client
    docker:
      - image: docker:18.09.4
    steps:
      - checkout
      - run: 
          name: Publish Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t marcussmallman/ideas-client:latest -t marcussmallman/ideas-client:$CIRCLE_BRANCH .
            docker push marcussmallman/ideas-client:$CIRCLE_BRANCH

workflows:
  version: 2.1
  ideas:
    jobs:
      - build-ui
      - build-server
      - publish-image:
          requires:
            - build-ui
            - build-server