version: 2.1
jobs:
  build-ui:
    docker:
      - image: node:8.15.1
    working_directory:  ~/project/client
    steps:
      - checkout
      - run:
          name: Build UI
          command: |
            npm install
            npm run lint
            npm run build
      - persist_to_workspace:
          root: client
          paths:
            - dist
  build-server:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory:  ~/project/client
    steps:
      - checkout
      - run:
          name: Build Server
          command: |
            dotnet restore
            dotnet publish -c release -o out -r linux-arm
      - persist_to_workspace:
          root: client
          paths:
            - out
  publish-image:
    machine: true
    working_directory: ~/project/client
    steps:
      - checkout
      - attach_workspace:
          at: client
      - run: 
          name: Publish Image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t marcussmallman/ideas-client:latest . # Support verson tag
            docker push marcussmallman/ideas-client:latest
workflows:
  version: 2.1
  ideas:
    jobs:
      - build-ui
      - build-server
      - publish-image:
          requires:
            - build-ui
            - build-server