version: 2.1

jobs:
  # Add build function job
  build-ui:
    docker:
      - image: node:8.15.1
    steps:
      - checkout
      - run:
          name: Build UI
          command: |
            cd client
            npm install
            npm run lint
            npm run build
  build-server:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Build UI
          command: |
            cd client
            dotnet restore
            dotnet publish -c release -o out -r linux-arm /client
  # Add publish docker image job

workflows:
  version: 2.1
  build:
    jobs:
      - build-ui
      - build-server