apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ideas
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: marcussmallman/ideas-client:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: client-service
  namespace: ideas
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ideas-client
  namespace: ideas
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client-service
          servicePort: web